# Generated by Django 3.2.13 on 2022-07-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(blank=True, max_length=200, null=True)),
                ('taxableAmount', models.FloatField(default=0.0)),
                ('gstAmount', models.FloatField(default=0.0)),
                ('otherCharges', models.FloatField(default=0.0)),
                ('roundOff', models.FloatField(default=0.0)),
                ('grandTotal', models.FloatField(default=0.0)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceDate', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('supplierID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='home.supplier')),
            ],
            options={
                'verbose_name_plural': 'h) Purchase List',
            },
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('gst', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('net', models.FloatField(default=0.0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('productID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='home.product')),
                ('purchaseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='home.purchase')),
            ],
            options={
                'verbose_name_plural': 'i) Purchase Product List',
            },
        ),
    ]
