# Generated by Django 3.2.13 on 2022-07-08 11:44

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0005_purchase_purchaseproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('customerCode', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='customer/img',
                                                        variations={'large': (600, 400), 'medium': (300, 200),
                                                                    'thumbnail': (50, 50, True)})),
                ('idProofFront',
                 stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='customer/img',
                                               variations={'large': (600, 400), 'medium': (300, 200),
                                                           'thumbnail': (50, 50, True)})),
                ('idProofBack',
                 stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='customer/img',
                                               variations={'large': (600, 400), 'medium': (300, 200),
                                                           'thumbnail': (50, 50, True)})),
                ('latitude', models.CharField(default='0.0', max_length=200)),
                ('longitude', models.CharField(default='0.0', max_length=200)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('addedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='home.staffuser')),
            ],
            options={
                'verbose_name_plural': 'j).Customer List',
            },
        ),
    ]
