# Generated by Django 3.2.13 on 2022-07-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=200, null=True)),
                ('productName', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.FloatField(default=0.0)),
                ('advancePaid', models.FloatField(default=0.0)),
                ('tenureInMonth', models.FloatField(default=0.0)),
                ('emiAmount', models.FloatField(default=0.0)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('latitude', models.CharField(default='0.0', max_length=200)),
                ('longitude', models.CharField(default='0.0', max_length=200)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('installmentStartDate', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('addedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='AddedBy', to='home.staffuser')),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='AssignedTo', to='home.staffuser')),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='home.customer')),
                ('productID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='home.product')),
            ],
            options={
                'verbose_name_plural': 'k) Sales List',
            },
        ),
    ]
