# Generated by Django 3.2.13 on 2022-07-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0009_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='isReassigned',
            field=models.BooleanField(default=False),
        ),
    ]
