# Generated by Django 3.2.13 on 2022-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0010_auto_20220714_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
