# Generated by Django 3.2.13 on 2022-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0013_auto_20220721_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
