# Generated by Django 3.2.13 on 2022-07-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0015_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
