# Generated by Django 3.2.13 on 2022-07-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0017_sale_saleno'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='emiAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
