# Generated by Django 3.2.13 on 2022-08-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0018_installment_emiamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAndLogoutStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusType', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(default='0.0', max_length=200)),
                ('longitude', models.CharField(default='0.0', max_length=200)),
                ('isDeleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='home.staffuser')),
            ],
            options={
                'verbose_name_plural': 'O) Login-Logout',
            },
        ),
    ]
